# Generated by Django 6.0.4 on 2026-04-22 07:50

import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default=inventory.models._generate_sku, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(default='C51B56F4C001408', max_length=50, unique=True),
        ),
    ]
