# Generated by Django 6.0.4 on 2026-04-22 07:50

import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_sku_alter_transaction_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(default=inventory.models._generate_transaction_id, max_length=50, unique=True),
        ),
    ]
